const person = {
    "pesrsons":[
       {
          "name":"Ganesh",
          "age":"25"
       },
       {
          "name":"Ramesh",
          "age":"26"
       },
       {
          "name":"Suresh",
          "age":"27"
       },
       {
            "name":"Rajesh",
            "age":"28"
        },
        {
            "name":"Someone",
            "age":"29"
        },
        {
            "name":"anotherone",
            "age":"30"
        }
    ]
 }